# GitHub workflow 

name: My-CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone my repo 
        uses: actions/checkout@v1

      - name: Run a multi-line script
        run: |
          echo "hello"
